defaults:
  - single
  - _self_

data:
  fold_dir: '/data/pathology/projects/ais-cap/dataset/tcga/brca/survival/5fold-cv_narrowed'

features_dir: '/data/pathology/projects/ais-cap/code/git/cpg/hipt/output/tcga_brca_all_slides/features/global'
output_dir: 'output/tcga_brca'
experiment_name: 'narrowed_multi_concat_pos_encoding'
level: 'global'

nepochs: 50

testing:
  retrieve_checkpoint: 'latest'

model:
  agg_method: 'concat'
  slide_pos_embed:
    use: True
    learned: False
    type: '1d'
    max_seq_len: 5000
